// Liste de vocabulaire pré-chargée au premier lancement (si aucune sauvegarde locale n'existe).
// IMPORTANT : le statut initial est "non_teste", jamais "a_revoir" — un mot jamais posé en
// session ne doit pas être confondu avec un mot sur lequel l'enfant s'est trompé.
//
// Pour mettre à jour cette liste (nouveau vocabulaire ajouté par l'enfant, à repousser sur
// GitHub) : utilise le menu ⋮ de l'écran "Mes Mots" > "Exporter la liste de mots (sans
// progression)", puis remplace le contenu du tableau ci-dessous par le fichier obtenu.

export const WORDS_SEED = [
  { id: 1, motAnglais: "good morning", traductionFrancais: "bonjour (matin)", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 2, motAnglais: "good afternoon", traductionFrancais: "bon après-midi", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 3, motAnglais: "good evening", traductionFrancais: "bonsoir", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 4, motAnglais: "good night", traductionFrancais: "bonne nuit", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 5, motAnglais: "good bye / bye", traductionFrancais: "au revoir", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 6, motAnglais: "hello / hi", traductionFrancais: "salut / bonjour", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 7, motAnglais: "see you", traductionFrancais: "à bientôt", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 8, motAnglais: "see you tomorrow", traductionFrancais: "à demain", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 9, motAnglais: "how are you?", traductionFrancais: "comment vas-tu ?", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 10, motAnglais: "fine", traductionFrancais: "bien / en forme", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 11, motAnglais: "happy", traductionFrancais: "content / heureux", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 12, motAnglais: "sad", traductionFrancais: "triste", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 13, motAnglais: "excited", traductionFrancais: "très impatient / excité", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 14, motAnglais: "angry", traductionFrancais: "en colère", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 15, motAnglais: "worried", traductionFrancais: "inquiet", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 16, motAnglais: "surprised", traductionFrancais: "surpris", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 17, motAnglais: "hot", traductionFrancais: "avoir chaud", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 18, motAnglais: "cold", traductionFrancais: "avoir froid", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 19, motAnglais: "thirsty", traductionFrancais: "avoir soif", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 20, motAnglais: "scared", traductionFrancais: "avoir peur", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 21, motAnglais: "tired", traductionFrancais: "fatigué", dateAjout: "2026-09-17", statut: "non_teste" },
  { id: 22, motAnglais: "board", traductionFrancais: "tableau", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 23, motAnglais: "scissors", traductionFrancais: "ciseaux", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 24, motAnglais: "desk", traductionFrancais: "bureau", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 25, motAnglais: "eraser", traductionFrancais: "gomme", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 26, motAnglais: "glue stick", traductionFrancais: "bâton de colle", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 27, motAnglais: "pencil", traductionFrancais: "crayon à papier", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 28, motAnglais: "school bag", traductionFrancais: "cartable", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 29, motAnglais: "pen", traductionFrancais: "stylo", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 30, motAnglais: "mouse", traductionFrancais: "souris", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 31, motAnglais: "tape", traductionFrancais: "scotch / ruban adhésif", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 32, motAnglais: "chair", traductionFrancais: "chaise", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 33, motAnglais: "ruler", traductionFrancais: "règle", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 34, motAnglais: "correction tape", traductionFrancais: "ruban correcteur (blanco)", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 35, motAnglais: "pencil case", traductionFrancais: "trousse", dateAjout: "2026-09-18", statut: "non_teste" },
  { id: 36, motAnglais: "read", traductionFrancais: "lire", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 37, motAnglais: "look at", traductionFrancais: "regarder", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 38, motAnglais: "answer", traductionFrancais: "répondre", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 39, motAnglais: "complete", traductionFrancais: "compléter", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 40, motAnglais: "write", traductionFrancais: "écrire", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 41, motAnglais: "circle", traductionFrancais: "entourer", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 42, motAnglais: "watch", traductionFrancais: "observer / regarder", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 43, motAnglais: "listen to", traductionFrancais: "écouter", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 44, motAnglais: "underline", traductionFrancais: "souligner", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 45, motAnglais: "match", traductionFrancais: "relier / associer", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 46, motAnglais: "checked", traductionFrancais: "coché / vérifié", dateAjout: "2026-09-19", statut: "non_teste" },
  { id: 47, motAnglais: "zero", traductionFrancais: "zéro", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 48, motAnglais: "one", traductionFrancais: "un", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 49, motAnglais: "two", traductionFrancais: "deux", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 50, motAnglais: "three", traductionFrancais: "trois", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 51, motAnglais: "four", traductionFrancais: "quatre", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 52, motAnglais: "five", traductionFrancais: "cinq", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 53, motAnglais: "six", traductionFrancais: "six", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 54, motAnglais: "seven", traductionFrancais: "sept", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 55, motAnglais: "eight", traductionFrancais: "huit", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 56, motAnglais: "nine", traductionFrancais: "neuf", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 57, motAnglais: "ten", traductionFrancais: "dix", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 58, motAnglais: "eleven", traductionFrancais: "onze", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 59, motAnglais: "twelve", traductionFrancais: "douze", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 60, motAnglais: "thirteen", traductionFrancais: "treize", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 61, motAnglais: "fourteen", traductionFrancais: "quatorze", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 62, motAnglais: "fifteen", traductionFrancais: "quinze", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 63, motAnglais: "sixteen", traductionFrancais: "seize", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 64, motAnglais: "seventeen", traductionFrancais: "dix-sept", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 65, motAnglais: "eighteen", traductionFrancais: "dix-huit", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 66, motAnglais: "nineteen", traductionFrancais: "dix-neuf", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 67, motAnglais: "twenty", traductionFrancais: "vingt", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 68, motAnglais: "thirty", traductionFrancais: "trente", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 69, motAnglais: "forty", traductionFrancais: "quarante", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 70, motAnglais: "fifty", traductionFrancais: "cinquante", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 71, motAnglais: "sixty", traductionFrancais: "soixante", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 72, motAnglais: "seventy", traductionFrancais: "soixante-dix", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 73, motAnglais: "eighty", traductionFrancais: "quatre-vingts", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 74, motAnglais: "ninety", traductionFrancais: "quatre-vingt-dix", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 75, motAnglais: "one hundred", traductionFrancais: "cent", dateAjout: "2026-09-20", statut: "non_teste" },
  { id: 76, motAnglais: "Monday", traductionFrancais: "lundi", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 77, motAnglais: "Tuesday", traductionFrancais: "mardi", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 78, motAnglais: "Wednesday", traductionFrancais: "mercredi", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 79, motAnglais: "Thursday", traductionFrancais: "jeudi", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 80, motAnglais: "Friday", traductionFrancais: "vendredi", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 81, motAnglais: "Saturday", traductionFrancais: "samedi", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 82, motAnglais: "Sunday", traductionFrancais: "dimanche", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 83, motAnglais: "January", traductionFrancais: "janvier", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 84, motAnglais: "February", traductionFrancais: "février", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 85, motAnglais: "March", traductionFrancais: "mars", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 86, motAnglais: "April", traductionFrancais: "avril", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 87, motAnglais: "May", traductionFrancais: "mai", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 88, motAnglais: "June", traductionFrancais: "juin", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 89, motAnglais: "July", traductionFrancais: "juillet", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 90, motAnglais: "August", traductionFrancais: "août", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 91, motAnglais: "September", traductionFrancais: "septembre", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 92, motAnglais: "October", traductionFrancais: "octobre", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 93, motAnglais: "November", traductionFrancais: "novembre", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 94, motAnglais: "December", traductionFrancais: "décembre", dateAjout: "2026-09-21", statut: "non_teste" },
  { id: 95, motAnglais: "alien", traductionFrancais: "extraterrestre", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 96, motAnglais: "bike", traductionFrancais: "vélo", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 97, motAnglais: "eagle", traductionFrancais: "aigle", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 98, motAnglais: "fish", traductionFrancais: "poisson", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 99, motAnglais: "ice cream", traductionFrancais: "glace", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 100, motAnglais: "juice", traductionFrancais: "jus", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 101, motAnglais: "monkey", traductionFrancais: "singe", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 102, motAnglais: "nuts", traductionFrancais: "noix", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 103, motAnglais: "queen", traductionFrancais: "reine", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 104, motAnglais: "tomato", traductionFrancais: "tomate", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 105, motAnglais: "water", traductionFrancais: "eau", dateAjout: "2026-09-22", statut: "non_teste" },
  { id: 106, motAnglais: "black", traductionFrancais: "noir", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 107, motAnglais: "white", traductionFrancais: "blanc", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 108, motAnglais: "green", traductionFrancais: "vert", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 109, motAnglais: "blue", traductionFrancais: "bleu", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 110, motAnglais: "red", traductionFrancais: "rouge", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 111, motAnglais: "yellow", traductionFrancais: "jaune", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 112, motAnglais: "orange", traductionFrancais: "orange", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 113, motAnglais: "grey / gray", traductionFrancais: "gris", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 114, motAnglais: "pink", traductionFrancais: "rose", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 115, motAnglais: "brown", traductionFrancais: "marron", dateAjout: "2026-09-23", statut: "non_teste" },
  { id: 116, motAnglais: "purple", traductionFrancais: "violet", dateAjout: "2026-09-23", statut: "non_teste" }
];
